name: rentro_car
description: "A project Allows user to Rent and Book Cars"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3


#------------ PAKAGES --------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  cupertino_icons: ^1.0.8
  # get: ^4.6.5
  # get_storage: ^2.0.3
  # google_fonts: ^3.0.1
  # intl: ^0.17.0
  # provider: ^6.0.5
  # http: ^0.13.5
  # logger: ^1.1.0
  # url_luncher: ^6.1.12
  flutter_native_splash: ^2.4.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  dio: ^5.7.0
  dartz: ^0.10.1
  jwt_decoder: ^2.0.1
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # flutter_native_splash:
  #   color: "#ffffff"
  #   image: assets/images/splash.png
  # flutter_icons:
  #   android: "luancher_icon"
  #   ios: true
  #   image_path: "assets/images/logo.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
